global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # NIKKOTRADER Agents Monitoring
  - job_name: 'nikkotrader-agents'
    scrape_interval: 5s
    static_configs:
      - targets: 
        - 'master-agent:8080'
        - 'market-data-agent:8080'
        - 'strategy-agents:8080'
        - 'risk-agent:8080'
        - 'performance-agent:8080'
        - 'notification-agent:8080'
    metrics_path: '/metrics'

  # Backend API Monitoring
  - job_name: 'nikkotrader-api'
    scrape_interval: 10s
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'

  # Redis Monitoring
  - job_name: 'redis'
    scrape_interval: 30s
    static_configs:
      - targets: ['redis:6379']

  # PostgreSQL Monitoring  
  - job_name: 'postgres'
    scrape_interval: 30s
    static_configs:
      - targets: ['postgres:5432']

  # RabbitMQ Monitoring
  - job_name: 'rabbitmq'
    scrape_interval: 30s
    static_configs:
      - targets: ['rabbitmq:15672']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093 